### ISSUE TITLE
Shortcut for org-agenda

### ISSUE THREAD

**Issue by dariushazimi** [myTerminal/super-emacs#2]
Hi, I am using the super-emacs. Prior to super emacs I was able to press C c a a  and open the agenda view. Now this short cut does not work any more. Do you know where I can look for or how to bring up org agenda quickly with a short cut?

thanks.

**Comment by myTerminal** [comment]
Could you please share with me your previous configuration? I am not able to bring up the agenda view even on stock emacs.

**Comment by myTerminal** [comment]
Does not seem to be issue, closing it for now.
