### ISSUE TITLE
Changes on configuration nuke font changing.

### ISSUE THREAD

**Issue by fabiocosta0305** [myTerminal/super-emacs#3]
# Issue:

By exchanging the configurations (sometimes even updating packages on MELPA), all customized configurations saved via `menu-bar-options-save` goes away, including font setup

# Replicate:

1. Change your font via `menu-set-font` and save it via `menu-bar-options-save`
2. Close and open emacs
3. Change other configurations and/or install/update new packages from MELPA
4. Close and open emacs

**Comment by myTerminal** [comment]
I do not know how this one slipped and managed to stay undiscovered for exactly 1 year 2 days :)

Sorry about that, I'll investigate.

**Comment by myTerminal** [comment]
I never used `menu-set-font` and `menu-bar-options-save` personally but I read about it a bit on the web and spent some time on replicating this issue.

As per my configuration, all customization is supposed to be saved to the file 'super-emacs\custom.el'. According to what I know, this file autogenerated and contains several lines of Elisp code specifying most (if not all) of your customization.

I tried changing the font-style and font-family using `menu-set-font` and then called `menu-bar-options-save`, with and without forcing the customization to be saved to 'custom.el', but did not see it being recorded anywhere in the emacs directory. In fact, just changing the font (step-1) and restarting emacs (step-2) lost all the changes to font settings performed using that option.

I'm not sure if that would be appropriate to ask, but if you could help me with a more specific example of how this feature is supposed to work (and you still find this as a defect), we should be able to fix this better.

**Comment by myTerminal** [comment]
Closing this for now, feel free to re-open if needed.
