### ISSUE TITLE
Mac: App exposé (three finger drag down) I want to see the file names

### ISSUE THREAD

**Issue by ericllazarus** [myTerminal/super-emacs#4]
Every one of the windows says Super-Emacs rather than the file name.  I know I'm using Super Emacs and that's great. But I want to see the file name so I can jump to the right window.

**Comment by myTerminal** [comment]
Just pushed changes to make it like "*\<file-name\>* - super-emacs". Please give it a try when you get a chance and let me know how it looks.

**Comment by ericllazarus** [comment]
That works great! Thanks! You rock.

**Comment by myTerminal** [comment]
Closing as this is fixed now.
