### ISSUE TITLE
tab should auto complete file names

### ISSUE THREAD

**Issue by ericllazarus** [myTerminal/super-emacs#6]
I'm so used to typing find file (^x^f) and using tab to complete director and file names. Any way we can turn that back on w/o removing helm? 

https://emacs.stackexchange.com/questions/33727/how-does-spacemacs-allow-tab-completion-in-helm

THANKS!

**Comment by myTerminal** [comment]
I replaced helm with ivy (along with counsel and swiper), which are lighter, faster and opinionatedly superior. ivy uses tab completion and hence it should solve the problem of non-standard input.

@ericllazarus, kindly let me know how it feels now.

**Comment by myTerminal** [comment]
I'm closing this issue as the problem is not there anymore. Feel free to re-open in case of any issues.
