### ISSUE TITLE
.Rmd files are not seen as r markdown files (but .rmd files are )

### ISSUE THREAD

**Issue by ericllazarus** [myTerminal/super-emacs#7]
Can you fix that? Thanks!

**Comment by myTerminal** [comment]
I still have this close to the top of my list, will pick it up soon.

**Comment by myTerminal** [comment]
I just verified and found that according to the code, there should be no difference between `.rmd` and `.Rmd` file extensions. I found the below piece of code that associated both the variations:

    ("\\.[rR]md\\'" . poly-markdown+r-mode)

I also tested opening a file with an *.Rmd* extension and (not to my surprise) it seems to work exactly like *.rmd* files. Could you please try it once more?

Just in case it still doesn't work for you, I'd suggest adding the below line in a custom *.el* file and restart Emacs.

    (add-to-list 'auto-mode-alist '("\\.Rmd\\'" . poly-markdown+r-mode))

Let me know if it still doesn't work for you in which case we'll have to figure out something else.

**Comment by ericllazarus** [comment]
I can't reproduce the problem. I'll try again but as of now, both .rmd and .Rmd work fine. THANKS!

**Comment by myTerminal** [comment]
I'll close this one for now then.
